language: python
python:
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
- pip install twine
script: nosetests tests/ --with-coverage --cover-package=tornadorax
deploy:
  provider: pypi
  user: joshmarshall
  password:
    secure: KO2EtEfr1JTcOga0/4fuNxSsPE/PFb6ZMY1OiG07uRasmEL4cebGcoVcKBOch4cOktarAzZ9Fndh9kIJIPXyTqKWLBm4988dZma4/O5m5hpaexuhJPXHKFU5dJtj5J6YFR9W8OFvqKD59M85bd+qlqTPVRqOzw/1/kW1EDHcNxU=
  on:
    tags: true
    repo: joshmarshall/tornadorax
    branch: master
